// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.0
// source: hiit.proto

package hiit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HIITActivity_Type int32

const (
	HIITActivity_UNKNOWN           HIITActivity_Type = 0
	HIITActivity_ROUTINE_CHANGE    HIITActivity_Type = 1
	HIITActivity_INTERVAL_COMPLETE HIITActivity_Type = 2
	HIITActivity_WINNER            HIITActivity_Type = 3
)

// Enum value maps for HIITActivity_Type.
var (
	HIITActivity_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ROUTINE_CHANGE",
		2: "INTERVAL_COMPLETE",
		3: "WINNER",
	}
	HIITActivity_Type_value = map[string]int32{
		"UNKNOWN":           0,
		"ROUTINE_CHANGE":    1,
		"INTERVAL_COMPLETE": 2,
		"WINNER":            3,
	}
)

func (x HIITActivity_Type) Enum() *HIITActivity_Type {
	p := new(HIITActivity_Type)
	*p = x
	return p
}

func (x HIITActivity_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HIITActivity_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_hiit_proto_enumTypes[0].Descriptor()
}

func (HIITActivity_Type) Type() protoreflect.EnumType {
	return &file_hiit_proto_enumTypes[0]
}

func (x HIITActivity_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HIITActivity_Type.Descriptor instead.
func (HIITActivity_Type) EnumDescriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{13, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Count    int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Interval string `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Data) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Data) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type DataSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Session *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *DataSession) Reset() {
	*x = DataSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSession) ProtoMessage() {}

func (x *DataSession) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSession.ProtoReflect.Descriptor instead.
func (*DataSession) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{2}
}

func (x *DataSession) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataSession) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type RoutineChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routine string `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *RoutineChange) Reset() {
	*x = RoutineChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineChange) ProtoMessage() {}

func (x *RoutineChange) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineChange.ProtoReflect.Descriptor instead.
func (*RoutineChange) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{3}
}

func (x *RoutineChange) GetRoutine() string {
	if x != nil {
		return x.Routine
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exercise string `protobuf:"bytes,2,opt,name=exercise,proto3" json:"exercise,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetExercise() string {
	if x != nil {
		return x.Exercise
	}
	return ""
}

type WorkoutUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Score int32  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *WorkoutUser) Reset() {
	*x = WorkoutUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkoutUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutUser) ProtoMessage() {}

func (x *WorkoutUser) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutUser.ProtoReflect.Descriptor instead.
func (*WorkoutUser) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{5}
}

func (x *WorkoutUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkoutUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkoutUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WorkoutUser) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CreateWaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host    *WorkoutUser `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Workout string       `protobuf:"bytes,2,opt,name=workout,proto3" json:"workout,omitempty"`
}

func (x *CreateWaitingRoomRequest) Reset() {
	*x = CreateWaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWaitingRoomRequest) ProtoMessage() {}

func (x *CreateWaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateWaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWaitingRoomRequest) GetHost() *WorkoutUser {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *CreateWaitingRoomRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

type WaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    *WorkoutUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Workout string       `protobuf:"bytes,2,opt,name=workout,proto3" json:"workout,omitempty"`
}

func (x *WaitingRoomRequest) Reset() {
	*x = WaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingRoomRequest) ProtoMessage() {}

func (x *WaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*WaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{7}
}

func (x *WaitingRoomRequest) GetUser() *WorkoutUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WaitingRoomRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

type WaitingRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host  *WorkoutUser   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Users []*WorkoutUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Start bool           `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
}

func (x *WaitingRoomResponse) Reset() {
	*x = WaitingRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitingRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingRoomResponse) ProtoMessage() {}

func (x *WaitingRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingRoomResponse.ProtoReflect.Descriptor instead.
func (*WaitingRoomResponse) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{8}
}

func (x *WaitingRoomResponse) GetHost() *WorkoutUser {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *WaitingRoomResponse) GetUsers() []*WorkoutUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *WaitingRoomResponse) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

type InviteWaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    *WorkoutUser `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To      *WorkoutUser `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Workout string       `protobuf:"bytes,3,opt,name=workout,proto3" json:"workout,omitempty"`
}

func (x *InviteWaitingRoomRequest) Reset() {
	*x = InviteWaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteWaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteWaitingRoomRequest) ProtoMessage() {}

func (x *InviteWaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteWaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*InviteWaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{9}
}

func (x *InviteWaitingRoomRequest) GetFrom() *WorkoutUser {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *InviteWaitingRoomRequest) GetTo() *WorkoutUser {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *InviteWaitingRoomRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

type StartWaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host    *WorkoutUser `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Workout string       `protobuf:"bytes,3,opt,name=workout,proto3" json:"workout,omitempty"`
}

func (x *StartWaitingRoomRequest) Reset() {
	*x = StartWaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartWaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWaitingRoomRequest) ProtoMessage() {}

func (x *StartWaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*StartWaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{10}
}

func (x *StartWaitingRoomRequest) GetHost() *WorkoutUser {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *StartWaitingRoomRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

type CreateDuoHIITRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *WorkoutUser `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Hiit string       `protobuf:"bytes,2,opt,name=hiit,proto3" json:"hiit,omitempty"`
}

func (x *CreateDuoHIITRequest) Reset() {
	*x = CreateDuoHIITRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDuoHIITRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDuoHIITRequest) ProtoMessage() {}

func (x *CreateDuoHIITRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDuoHIITRequest.ProtoReflect.Descriptor instead.
func (*CreateDuoHIITRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDuoHIITRequest) GetHost() *WorkoutUser {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *CreateDuoHIITRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

type JoinDuoHIITRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *WorkoutUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Hiit string       `protobuf:"bytes,2,opt,name=hiit,proto3" json:"hiit,omitempty"`
}

func (x *JoinDuoHIITRequest) Reset() {
	*x = JoinDuoHIITRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinDuoHIITRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinDuoHIITRequest) ProtoMessage() {}

func (x *JoinDuoHIITRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinDuoHIITRequest.ProtoReflect.Descriptor instead.
func (*JoinDuoHIITRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{12}
}

func (x *JoinDuoHIITRequest) GetUser() *WorkoutUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *JoinDuoHIITRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

type HIITActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hiit    string            `protobuf:"bytes,1,opt,name=hiit,proto3" json:"hiit,omitempty"`
	User    *WorkoutUser      `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Routine *HIITRoutine      `protobuf:"bytes,3,opt,name=routine,proto3" json:"routine,omitempty"`
	Type    HIITActivity_Type `protobuf:"varint,4,opt,name=type,proto3,enum=hiit.HIITActivity_Type" json:"type,omitempty"`
	Winner  *WorkoutUser      `protobuf:"bytes,5,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (x *HIITActivity) Reset() {
	*x = HIITActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIITActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIITActivity) ProtoMessage() {}

func (x *HIITActivity) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIITActivity.ProtoReflect.Descriptor instead.
func (*HIITActivity) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{13}
}

func (x *HIITActivity) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

func (x *HIITActivity) GetUser() *WorkoutUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HIITActivity) GetRoutine() *HIITRoutine {
	if x != nil {
		return x.Routine
	}
	return nil
}

func (x *HIITActivity) GetType() HIITActivity_Type {
	if x != nil {
		return x.Type
	}
	return HIITActivity_UNKNOWN
}

func (x *HIITActivity) GetWinner() *WorkoutUser {
	if x != nil {
		return x.Winner
	}
	return nil
}

type HIITRoutineInterval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HIITRoutineInterval) Reset() {
	*x = HIITRoutineInterval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIITRoutineInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIITRoutineInterval) ProtoMessage() {}

func (x *HIITRoutineInterval) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIITRoutineInterval.ProtoReflect.Descriptor instead.
func (*HIITRoutineInterval) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{14}
}

func (x *HIITRoutineInterval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HIITRoutine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exercise string               `protobuf:"bytes,2,opt,name=exercise,proto3" json:"exercise,omitempty"`
	Interval *HIITRoutineInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *HIITRoutine) Reset() {
	*x = HIITRoutine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIITRoutine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIITRoutine) ProtoMessage() {}

func (x *HIITRoutine) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIITRoutine.ProtoReflect.Descriptor instead.
func (*HIITRoutine) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{15}
}

func (x *HIITRoutine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HIITRoutine) GetExercise() string {
	if x != nil {
		return x.Exercise
	}
	return ""
}

func (x *HIITRoutine) GetInterval() *HIITRoutineInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

type HIITIntervalCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hiit    string       `protobuf:"bytes,1,opt,name=hiit,proto3" json:"hiit,omitempty"`
	User    *WorkoutUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Routine *HIITRoutine `protobuf:"bytes,3,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *HIITIntervalCompleteRequest) Reset() {
	*x = HIITIntervalCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIITIntervalCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIITIntervalCompleteRequest) ProtoMessage() {}

func (x *HIITIntervalCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIITIntervalCompleteRequest.ProtoReflect.Descriptor instead.
func (*HIITIntervalCompleteRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{16}
}

func (x *HIITIntervalCompleteRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

func (x *HIITIntervalCompleteRequest) GetUser() *WorkoutUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HIITIntervalCompleteRequest) GetRoutine() *HIITRoutine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type HIITSelectRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hiit    string       `protobuf:"bytes,1,opt,name=hiit,proto3" json:"hiit,omitempty"`
	User    *WorkoutUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Routine *HIITRoutine `protobuf:"bytes,3,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *HIITSelectRoutineRequest) Reset() {
	*x = HIITSelectRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIITSelectRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIITSelectRoutineRequest) ProtoMessage() {}

func (x *HIITSelectRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIITSelectRoutineRequest.ProtoReflect.Descriptor instead.
func (*HIITSelectRoutineRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{17}
}

func (x *HIITSelectRoutineRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

func (x *HIITSelectRoutineRequest) GetUser() *WorkoutUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HIITSelectRoutineRequest) GetRoutine() *HIITRoutine {
	if x != nil {
		return x.Routine
	}
	return nil
}

var File_hiit_proto protoreflect.FileDescriptor

var file_hiit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x69,
	0x69, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4e, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x56, 0x0a, 0x0b, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x07, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68, 0x69,
	0x69, 0x74, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x22, 0x35,
	0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x22, 0x5b, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75,
	0x74, 0x22, 0x55, 0x0a, 0x12, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x22, 0x7b, 0x0a, 0x13, 0x57, 0x61, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x7e, 0x0a, 0x18, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57,
	0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x77,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x22, 0x5a, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x61,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75,
	0x74, 0x22, 0x51, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6f, 0x48, 0x49,
	0x49, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x69, 0x69, 0x74, 0x22, 0x4f, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x75, 0x6f, 0x48,
	0x49, 0x49, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x69, 0x69, 0x74, 0x22, 0x9a, 0x02, 0x0a, 0x0c, 0x48, 0x49, 0x49, 0x54, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x2b,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x68,
	0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69,
	0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06,
	0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52,
	0x4f, 0x55, 0x54, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x01, 0x12,
	0x15, 0x0a, 0x11, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x5f, 0x43, 0x4f, 0x4d, 0x50,
	0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x49, 0x4e, 0x4e, 0x45, 0x52,
	0x10, 0x03, 0x22, 0x25, 0x0a, 0x13, 0x48, 0x49, 0x49, 0x54, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x0b, 0x48, 0x49, 0x49,
	0x54, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49,
	0x49, 0x54, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x85, 0x01, 0x0a, 0x1b,
	0x48, 0x49, 0x49, 0x54, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x69, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x69, 0x74, 0x12,
	0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48,
	0x49, 0x49, 0x54, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x18, 0x48, 0x49, 0x49, 0x54, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x69, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x72,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68,
	0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52,
	0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x32, 0xca, 0x05, 0x0a, 0x0b, 0x48, 0x49, 0x49,
	0x54, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12,
	0x13, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x1a, 0x0a, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x30, 0x01, 0x12, 0x25, 0x0a, 0x03, 0x50, 0x75, 0x62, 0x12, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x68,
	0x69, 0x69, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1e,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0f, 0x4a,
	0x6f, 0x69, 0x6e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x18,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x61,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1d, 0x2e, 0x68, 0x69, 0x69, 0x74,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x73, 0x12, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x1a, 0x1e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x75, 0x6f, 0x48, 0x49, 0x49, 0x54, 0x12, 0x1a, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6f, 0x48, 0x49, 0x49, 0x54, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69,
	0x6e, 0x44, 0x75, 0x6f, 0x48, 0x49, 0x49, 0x54, 0x12, 0x18, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x75, 0x6f, 0x48, 0x49, 0x49, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x14, 0x48, 0x49, 0x49, 0x54,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x21, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x43, 0x0a, 0x14, 0x44, 0x75, 0x6f, 0x48, 0x49, 0x49, 0x54, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x48, 0x49, 0x49, 0x54, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x68, 0x69, 0x69, 0x74, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hiit_proto_rawDescOnce sync.Once
	file_hiit_proto_rawDescData = file_hiit_proto_rawDesc
)

func file_hiit_proto_rawDescGZIP() []byte {
	file_hiit_proto_rawDescOnce.Do(func() {
		file_hiit_proto_rawDescData = protoimpl.X.CompressGZIP(file_hiit_proto_rawDescData)
	})
	return file_hiit_proto_rawDescData
}

var file_hiit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hiit_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_hiit_proto_goTypes = []interface{}{
	(HIITActivity_Type)(0),              // 0: hiit.HIITActivity.Type
	(*Empty)(nil),                       // 1: hiit.Empty
	(*Data)(nil),                        // 2: hiit.Data
	(*DataSession)(nil),                 // 3: hiit.DataSession
	(*RoutineChange)(nil),               // 4: hiit.RoutineChange
	(*Session)(nil),                     // 5: hiit.Session
	(*WorkoutUser)(nil),                 // 6: hiit.WorkoutUser
	(*CreateWaitingRoomRequest)(nil),    // 7: hiit.CreateWaitingRoomRequest
	(*WaitingRoomRequest)(nil),          // 8: hiit.WaitingRoomRequest
	(*WaitingRoomResponse)(nil),         // 9: hiit.WaitingRoomResponse
	(*InviteWaitingRoomRequest)(nil),    // 10: hiit.InviteWaitingRoomRequest
	(*StartWaitingRoomRequest)(nil),     // 11: hiit.StartWaitingRoomRequest
	(*CreateDuoHIITRequest)(nil),        // 12: hiit.CreateDuoHIITRequest
	(*JoinDuoHIITRequest)(nil),          // 13: hiit.JoinDuoHIITRequest
	(*HIITActivity)(nil),                // 14: hiit.HIITActivity
	(*HIITRoutineInterval)(nil),         // 15: hiit.HIITRoutineInterval
	(*HIITRoutine)(nil),                 // 16: hiit.HIITRoutine
	(*HIITIntervalCompleteRequest)(nil), // 17: hiit.HIITIntervalCompleteRequest
	(*HIITSelectRoutineRequest)(nil),    // 18: hiit.HIITSelectRoutineRequest
}
var file_hiit_proto_depIdxs = []int32{
	2,  // 0: hiit.DataSession.data:type_name -> hiit.Data
	5,  // 1: hiit.DataSession.session:type_name -> hiit.Session
	6,  // 2: hiit.CreateWaitingRoomRequest.host:type_name -> hiit.WorkoutUser
	6,  // 3: hiit.WaitingRoomRequest.user:type_name -> hiit.WorkoutUser
	6,  // 4: hiit.WaitingRoomResponse.host:type_name -> hiit.WorkoutUser
	6,  // 5: hiit.WaitingRoomResponse.users:type_name -> hiit.WorkoutUser
	6,  // 6: hiit.InviteWaitingRoomRequest.from:type_name -> hiit.WorkoutUser
	6,  // 7: hiit.InviteWaitingRoomRequest.to:type_name -> hiit.WorkoutUser
	6,  // 8: hiit.StartWaitingRoomRequest.host:type_name -> hiit.WorkoutUser
	6,  // 9: hiit.CreateDuoHIITRequest.host:type_name -> hiit.WorkoutUser
	6,  // 10: hiit.JoinDuoHIITRequest.user:type_name -> hiit.WorkoutUser
	6,  // 11: hiit.HIITActivity.user:type_name -> hiit.WorkoutUser
	16, // 12: hiit.HIITActivity.routine:type_name -> hiit.HIITRoutine
	0,  // 13: hiit.HIITActivity.type:type_name -> hiit.HIITActivity.Type
	6,  // 14: hiit.HIITActivity.winner:type_name -> hiit.WorkoutUser
	15, // 15: hiit.HIITRoutine.interval:type_name -> hiit.HIITRoutineInterval
	6,  // 16: hiit.HIITIntervalCompleteRequest.user:type_name -> hiit.WorkoutUser
	16, // 17: hiit.HIITIntervalCompleteRequest.routine:type_name -> hiit.HIITRoutine
	6,  // 18: hiit.HIITSelectRoutineRequest.user:type_name -> hiit.WorkoutUser
	16, // 19: hiit.HIITSelectRoutineRequest.routine:type_name -> hiit.HIITRoutine
	4,  // 20: hiit.HIITService.Sub:input_type -> hiit.RoutineChange
	3,  // 21: hiit.HIITService.Pub:input_type -> hiit.DataSession
	7,  // 22: hiit.HIITService.CreateWaitingRoom:input_type -> hiit.CreateWaitingRoomRequest
	8,  // 23: hiit.HIITService.JoinWaitingRoom:input_type -> hiit.WaitingRoomRequest
	11, // 24: hiit.HIITService.StartWaitingRoom:input_type -> hiit.StartWaitingRoomRequest
	10, // 25: hiit.HIITService.NotifyInvites:input_type -> hiit.InviteWaitingRoomRequest
	6,  // 26: hiit.HIITService.SubInvites:input_type -> hiit.WorkoutUser
	12, // 27: hiit.HIITService.CreateDuoHIIT:input_type -> hiit.CreateDuoHIITRequest
	13, // 28: hiit.HIITService.JoinDuoHIIT:input_type -> hiit.JoinDuoHIITRequest
	17, // 29: hiit.HIITService.HIITIntervalComplete:input_type -> hiit.HIITIntervalCompleteRequest
	18, // 30: hiit.HIITService.DuoHIITSelectRoutine:input_type -> hiit.HIITSelectRoutineRequest
	2,  // 31: hiit.HIITService.Sub:output_type -> hiit.Data
	1,  // 32: hiit.HIITService.Pub:output_type -> hiit.Empty
	9,  // 33: hiit.HIITService.CreateWaitingRoom:output_type -> hiit.WaitingRoomResponse
	9,  // 34: hiit.HIITService.JoinWaitingRoom:output_type -> hiit.WaitingRoomResponse
	1,  // 35: hiit.HIITService.StartWaitingRoom:output_type -> hiit.Empty
	1,  // 36: hiit.HIITService.NotifyInvites:output_type -> hiit.Empty
	10, // 37: hiit.HIITService.SubInvites:output_type -> hiit.InviteWaitingRoomRequest
	14, // 38: hiit.HIITService.CreateDuoHIIT:output_type -> hiit.HIITActivity
	14, // 39: hiit.HIITService.JoinDuoHIIT:output_type -> hiit.HIITActivity
	1,  // 40: hiit.HIITService.HIITIntervalComplete:output_type -> hiit.Empty
	1,  // 41: hiit.HIITService.DuoHIITSelectRoutine:output_type -> hiit.Empty
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_hiit_proto_init() }
func file_hiit_proto_init() {
	if File_hiit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hiit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkoutUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitingRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteWaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartWaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDuoHIITRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinDuoHIITRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIITActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIITRoutineInterval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIITRoutine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIITIntervalCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIITSelectRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hiit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hiit_proto_goTypes,
		DependencyIndexes: file_hiit_proto_depIdxs,
		EnumInfos:         file_hiit_proto_enumTypes,
		MessageInfos:      file_hiit_proto_msgTypes,
	}.Build()
	File_hiit_proto = out.File
	file_hiit_proto_rawDesc = nil
	file_hiit_proto_goTypes = nil
	file_hiit_proto_depIdxs = nil
}
