// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.0
// source: hiit.proto

package hiit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Count    int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Interval string `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Data) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Data) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type DataSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Session *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *DataSession) Reset() {
	*x = DataSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSession) ProtoMessage() {}

func (x *DataSession) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSession.ProtoReflect.Descriptor instead.
func (*DataSession) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{2}
}

func (x *DataSession) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataSession) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type RoutineChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routine string `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *RoutineChange) Reset() {
	*x = RoutineChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineChange) ProtoMessage() {}

func (x *RoutineChange) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineChange.ProtoReflect.Descriptor instead.
func (*RoutineChange) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{3}
}

func (x *RoutineChange) GetRoutine() string {
	if x != nil {
		return x.Routine
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exercise string `protobuf:"bytes,2,opt,name=exercise,proto3" json:"exercise,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetExercise() string {
	if x != nil {
		return x.Exercise
	}
	return ""
}

type HIITUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *HIITUser) Reset() {
	*x = HIITUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIITUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIITUser) ProtoMessage() {}

func (x *HIITUser) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIITUser.ProtoReflect.Descriptor instead.
func (*HIITUser) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{5}
}

func (x *HIITUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HIITUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HIITUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateWaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *HIITUser `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Hiit string    `protobuf:"bytes,2,opt,name=hiit,proto3" json:"hiit,omitempty"`
}

func (x *CreateWaitingRoomRequest) Reset() {
	*x = CreateWaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWaitingRoomRequest) ProtoMessage() {}

func (x *CreateWaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateWaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWaitingRoomRequest) GetHost() *HIITUser {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *CreateWaitingRoomRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

type WaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *HIITUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Hiit string    `protobuf:"bytes,2,opt,name=hiit,proto3" json:"hiit,omitempty"`
}

func (x *WaitingRoomRequest) Reset() {
	*x = WaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingRoomRequest) ProtoMessage() {}

func (x *WaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*WaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{7}
}

func (x *WaitingRoomRequest) GetUser() *HIITUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WaitingRoomRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

type WaitingRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host  *HIITUser   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Users []*HIITUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Start bool        `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
}

func (x *WaitingRoomResponse) Reset() {
	*x = WaitingRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitingRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingRoomResponse) ProtoMessage() {}

func (x *WaitingRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingRoomResponse.ProtoReflect.Descriptor instead.
func (*WaitingRoomResponse) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{8}
}

func (x *WaitingRoomResponse) GetHost() *HIITUser {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *WaitingRoomResponse) GetUsers() []*HIITUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *WaitingRoomResponse) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

type InviteWaitingRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *HIITUser `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *HIITUser `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Hiit string    `protobuf:"bytes,3,opt,name=hiit,proto3" json:"hiit,omitempty"`
}

func (x *InviteWaitingRoomRequest) Reset() {
	*x = InviteWaitingRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hiit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteWaitingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteWaitingRoomRequest) ProtoMessage() {}

func (x *InviteWaitingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteWaitingRoomRequest.ProtoReflect.Descriptor instead.
func (*InviteWaitingRoomRequest) Descriptor() ([]byte, []int) {
	return file_hiit_proto_rawDescGZIP(), []int{9}
}

func (x *InviteWaitingRoomRequest) GetFrom() *HIITUser {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *InviteWaitingRoomRequest) GetTo() *HIITUser {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *InviteWaitingRoomRequest) GetHiit() string {
	if x != nil {
		return x.Hiit
	}
	return ""
}

var File_hiit_proto protoreflect.FileDescriptor

var file_hiit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x69,
	0x69, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4e, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x56, 0x0a, 0x0b, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x07, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68, 0x69,
	0x69, 0x74, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x22, 0x35,
	0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x08, 0x48, 0x49, 0x49, 0x54, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x52, 0x0a, 0x18, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49,
	0x54, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x69, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x69, 0x74, 0x22,
	0x4c, 0x0a, 0x12, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x69, 0x74, 0x22, 0x75, 0x0a,
	0x13, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48,
	0x49, 0x49, 0x54, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x22, 0x72, 0x0a, 0x18, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x61,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x69, 0x74, 0x32, 0xf8, 0x02, 0x0a, 0x0b, 0x48, 0x49, 0x49,
	0x54, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12,
	0x13, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x1a, 0x0a, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x30, 0x01, 0x12, 0x25, 0x0a, 0x03, 0x50, 0x75, 0x62, 0x12, 0x11, 0x2e, 0x68, 0x69, 0x69, 0x74,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x68,
	0x69, 0x69, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1e,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0f, 0x4a,
	0x6f, 0x69, 0x6e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x18,
	0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3c, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x73, 0x12, 0x0e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x48, 0x49, 0x49, 0x54, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x1e, 0x2e, 0x68, 0x69, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57,
	0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x68, 0x69, 0x69, 0x74, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hiit_proto_rawDescOnce sync.Once
	file_hiit_proto_rawDescData = file_hiit_proto_rawDesc
)

func file_hiit_proto_rawDescGZIP() []byte {
	file_hiit_proto_rawDescOnce.Do(func() {
		file_hiit_proto_rawDescData = protoimpl.X.CompressGZIP(file_hiit_proto_rawDescData)
	})
	return file_hiit_proto_rawDescData
}

var file_hiit_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hiit_proto_goTypes = []interface{}{
	(*Empty)(nil),                    // 0: hiit.Empty
	(*Data)(nil),                     // 1: hiit.Data
	(*DataSession)(nil),              // 2: hiit.DataSession
	(*RoutineChange)(nil),            // 3: hiit.RoutineChange
	(*Session)(nil),                  // 4: hiit.Session
	(*HIITUser)(nil),                 // 5: hiit.HIITUser
	(*CreateWaitingRoomRequest)(nil), // 6: hiit.CreateWaitingRoomRequest
	(*WaitingRoomRequest)(nil),       // 7: hiit.WaitingRoomRequest
	(*WaitingRoomResponse)(nil),      // 8: hiit.WaitingRoomResponse
	(*InviteWaitingRoomRequest)(nil), // 9: hiit.InviteWaitingRoomRequest
}
var file_hiit_proto_depIdxs = []int32{
	1,  // 0: hiit.DataSession.data:type_name -> hiit.Data
	4,  // 1: hiit.DataSession.session:type_name -> hiit.Session
	5,  // 2: hiit.CreateWaitingRoomRequest.host:type_name -> hiit.HIITUser
	5,  // 3: hiit.WaitingRoomRequest.user:type_name -> hiit.HIITUser
	5,  // 4: hiit.WaitingRoomResponse.host:type_name -> hiit.HIITUser
	5,  // 5: hiit.WaitingRoomResponse.users:type_name -> hiit.HIITUser
	5,  // 6: hiit.InviteWaitingRoomRequest.from:type_name -> hiit.HIITUser
	5,  // 7: hiit.InviteWaitingRoomRequest.to:type_name -> hiit.HIITUser
	3,  // 8: hiit.HIITService.Sub:input_type -> hiit.RoutineChange
	2,  // 9: hiit.HIITService.Pub:input_type -> hiit.DataSession
	6,  // 10: hiit.HIITService.CreateWaitingRoom:input_type -> hiit.CreateWaitingRoomRequest
	7,  // 11: hiit.HIITService.JoinWaitingRoom:input_type -> hiit.WaitingRoomRequest
	9,  // 12: hiit.HIITService.NotifyInvites:input_type -> hiit.InviteWaitingRoomRequest
	5,  // 13: hiit.HIITService.SubInvites:input_type -> hiit.HIITUser
	1,  // 14: hiit.HIITService.Sub:output_type -> hiit.Data
	0,  // 15: hiit.HIITService.Pub:output_type -> hiit.Empty
	8,  // 16: hiit.HIITService.CreateWaitingRoom:output_type -> hiit.WaitingRoomResponse
	8,  // 17: hiit.HIITService.JoinWaitingRoom:output_type -> hiit.WaitingRoomResponse
	0,  // 18: hiit.HIITService.NotifyInvites:output_type -> hiit.Empty
	9,  // 19: hiit.HIITService.SubInvites:output_type -> hiit.InviteWaitingRoomRequest
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_hiit_proto_init() }
func file_hiit_proto_init() {
	if File_hiit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hiit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIITUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitingRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hiit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteWaitingRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hiit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hiit_proto_goTypes,
		DependencyIndexes: file_hiit_proto_depIdxs,
		MessageInfos:      file_hiit_proto_msgTypes,
	}.Build()
	File_hiit_proto = out.File
	file_hiit_proto_rawDesc = nil
	file_hiit_proto_goTypes = nil
	file_hiit_proto_depIdxs = nil
}
